### ISSUE TITLE
Error thrown if "Alternate URL Redirection Method" is set to "No Redirect" on Mura 6.2.6160

### ISSUE THREAD

**Issue by jeaguilar** [sebduggan/muraURLTools#37]
The following error thrown if "Alternate URL Redirection Method" is set to "No Redirect" on Mura 6.2.6160:

```
Can't cast String [] to a boolean at lucee.runtime.op.Caster.toBooleanValue(Unknown Source):-1 at lucee.runtime.op.Caster.toBooleanValue(Unknown Source):-1 at content.contentserver_cfc$cf.udfCall2(/var/www/www.example.com/requirements/mura/content/contentServer.cfc:810):810 at content.contentserver_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentServer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source):-1 at content.contentrenderer_cfc$cf.udfCall6(/var/www/www.example.com/requirements/mura/content/contentRenderer.cfc:1563):1563 at content.contentrenderer_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentRenderer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.type.scope.UndefinedImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at content.contentrenderer_cfc$cf.udfCall6(/var/www/www.example.com/requirements/mura/content/contentRenderer.cfc:1664):1664 at content.contentrenderer_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentRenderer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source):-1 at urltools.eventhandler_cfc$cf.udfCall(/var/www/www.example.com/plugins/URLTools/eventHandler.cfc:184):184 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.tag.Invoke.doComponent(Unknown Source):-1 at lucee.runtime.tag.Invoke.doEndTag(Unknown Source):-1 at plugin.pluginmanager_cfc$cf.udfCall3(/var/www/www.example.com/requirements/mura/plugin/pluginManager.cfc:1564):1564 at plugin.pluginmanager_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/plugin/pluginManager.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.type.scope.UndefinedImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at plugin.pluginmanager_cfc$cf.udfCall3(/var/www/www.example.com/requirements/mura/plugin/pluginManager.cfc:1257):1257 at plugin.pluginmanager_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/plugin/pluginManager.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at handler.standardeventshandler_cfc$cf.udfCall3(/var/www/www.example.com/requirements/mura/Handler/standardEventsHandler.cfc:415):415 at handler.standardeventshandler_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/Handler/standardEventsHandler.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source):-1 at lucee.runtime.tag.Invoke.doComponent(Unknown Source):-1 at lucee.runtime.tag.Invoke.doEndTag(Unknown Source):-1 at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/plugin/pluginStandardEventWrapper.cfc:89):89 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at content.contentserver_cfc$cf.udfCall2(/var/www/www.example.com/requirements/mura/content/contentServer.cfc:764):764 at content.contentserver_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentServer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.type.scope.UndefinedImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at content.contentserver_cfc$cf.udfCall1(/var/www/www.example.com/requirements/mura/content/contentServer.cfc:257):257 at content.contentserver_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentServer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.type.scope.UndefinedImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at content.contentserver_cfc$cf.udfCall1(/var/www/www.example.com/requirements/mura/content/contentServer.cfc:307):307 at content.contentserver_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentServer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at content.contentserver_cfc$cf.udfCall2(/var/www/www.example.com/requirements/mura/content/contentServer.cfc:644):644 at content.contentserver_cfc$cf.udfCall(/var/www/www.example.com/requirements/mura/content/contentServer.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(Unknown Source):-1 at lucee.runtime.type.UDFImpl._call(Unknown Source):-1 at lucee.runtime.type.UDFImpl.call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl._call(Unknown Source):-1 at lucee.runtime.ComponentImpl.call(Unknown Source):-1 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(Unknown Source):-1 at lucee.runtime.PageContextImpl.getFunction(Unknown Source):-1 at index_cfm$cf.call(/var/www/www.example.com/index.cfm:47):47 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1 at lucee.runtime.listener.ModernAppListener._onRequest(Unknown Source):-1 at lucee.runtime.listener.MixedAppListener.onRequest(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.PageContextImpl.execute(Unknown Source):-1 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(Unknown Source):-1 at lucee.loader.servlet.CFMLServlet.service(Unknown Source):-1 at javax.servlet.http.HttpServlet.service(HttpServlet.java:725):725 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219):219 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501):501 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673):673 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537):537 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085):1085 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658):658 at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222):222 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556):1556 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513):1513 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61 at java.lang.Thread.run(Thread.java:745):745
```

The error does not occur if "Alternate URL Redirection Method" is set to "Redirect". This error did not occur in Mura 6.1.x.

Error occurs in both Lucee (4.5.1.000) and Railo (4.2.1.001), OSX and Ubuntu 12.04.

**Comment by jeaguilar** [comment]
OK, I traced the issue back to the following commit:

[Adding new hashURLS settings.ini.cfm and contentRenderer setting](https://github.com/blueriver/MuraCMS/commit/3c279dc694c2c3bc5798c171472d28995f185f22)

Paging Matt Levine.

The issue here is that "" is assumed to be boolean false. (While YesNoFormat("") returns "No" (CF10) and "false" (Railo/Lucee), isBoolean("") returns "NO" (CF10) and "false" (Railo/Lucee)).

I'm guessing that the fix is to set these to 0 if the intention is to override the settings.ini.cfm value as false but I'll let the code writer weigh in.

Cheers.

**Comment by sebduggan** [comment]
Doesn't seem to be an issue now.
